### ISSUE TITLE
Another crash on Darwin!

### ISSUE THREAD

**Issue by jathanism** [coxley/nsot_sync#4]
```
$ nsot_sync --version
nsot_sync, version 0.4
$ nsot_sync simple
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR jathy.local: "{\"status\":\"error\",\"error\":{\"message\":{\"name\":\"Invalid name: u'jathy.local'.\"},\"code\":400}}"
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR 192.168.0.16/32: "{\"status\":\"error\",\"error\":{\"message\":\"IP Address needs base network.\",\"code\":400}}"
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR fe80::7a31:c1ff:febd:10/128: "{\"status\":\"error\",\"error\":{\"message\":\"IP Address needs base network.\",\"code\":400}}"
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR fe80::78c9:ddff:fec7:b825/128: "{\"status\":\"error\",\"error\":{\"message\":\"IP Address needs base network.\",\"code\":400}}"
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR fe80::7862:d2c5:d1da:adc8/128: "{\"status\":\"error\",\"error\":{\"message\":\"IP Address needs base network.\",\"code\":400}}"
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR fdab:e448:4ba:235c:7862:d2c5:d1da:adc8/128: "{\"status\":\"error\",\"error\":{\"message\":\"IP Address needs base network.\",\"code\":400}}"
2016-02-24 19:11:11 jathy.local nsot_sync.drivers.base_driver[8936] ERROR fe80::a28:c221:7a22:df4e/128: "{\"status\":\"error\",\"error\":{\"message\":\"IP Address needs base network.\",\"code\":400}}"
Traceback (most recent call last):
  File "/Users/jathan/sandbox/virtualenvs/pynsot/bin/nsot_sync", line 9, in <module>
    load_entry_point('nsot-sync==0.4', 'console_scripts', 'nsot_sync')()
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/nsot_sync/cli.py", line 93, in main
    cli(obj={})  # obj is for sharing things between click contexts
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/nsot_sync/commands/simple.py", line 22, in cli
    driver.handle_resources()
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/nsot_sync/drivers/base_driver.py", line 74, in handle_resources
    for interface in resources['interfaces']]
  File "/Users/jathan/sandbox/virtualenvs/pynsot/lib/python2.7/site-packages/nsot_sync/drivers/base_driver.py", line 147, in handle_interface
    interface['device'] = int(interface['device'])
ValueError: invalid literal for int() with base 10: 'jathy.local'
```

**Comment by coxley** [comment]
Thanks for the issue!

The first error, device not being created, comes from dropbox/nsot#157 - that being said this hostname should be `jathy` and not `jathy.local`

On linux, `gethostname()` returns just that but apparently Darwin returns the FQDN. To get around this I've just commited a change to always split on `.`

The other errors come from not having a base network. This is a valid error, though it's not straightforward nor pretty. I'm getting ready to commit a change to make it more obvious what action needs done on the user's part.
